"""Emitter-Aware Belief-State Expectimax Planner with Stochastic Branch-and-Bound.

SmartScan V2 Lookahead Engine:
- Evaluates Top-K candidate actions generated by SmartDiscountedUCB.
- Alternates Decision nodes and Chance nodes (HIT / MISS branches).
- Uses probabilistic belief propagation (no fake I/Q or CNN generation).
- Features dynamic future-node candidate selection, cumulative path probability pruning,
  optimistic branch-and-bound pruning, and state transposition caching.
- Strict compute budgets with automatic fallback to UCB top-1.
"""

from __future__ import annotations

from dataclasses import dataclass
import time
import numpy as np

from scheduler.track2_core import NUM_BANDS


@dataclass
class BeliefState:
    """Compact, copyable belief state for stochastic tree search."""
    band_belief: np.ndarray          # [NUM_BANDS], float32
    band_uncertainty: np.ndarray     # [NUM_BANDS], float32
    scan_age: np.ndarray             # [NUM_BANDS], float32
    ucb_values: np.ndarray           # [NUM_BANDS], float32
    ucb_counts: np.ndarray           # [NUM_BANDS], float32
    investigation_priority: np.ndarray # [NUM_BANDS], float32
    last_band: int | None

    def clone(self) -> BeliefState:
        return BeliefState(
            band_belief=self.band_belief.copy(),
            band_uncertainty=self.band_uncertainty.copy(),
            scan_age=self.scan_age.copy(),
            ucb_values=self.ucb_values.copy(),
            ucb_counts=self.ucb_counts.copy(),
            investigation_priority=self.investigation_priority.copy(),
            last_band=self.last_band,
        )


def _hash_state(state: BeliefState, depth: int) -> int:
    """Computes a quantized integer hash for transposition table memoization."""
    # Discretize continuous vectors into coarse buckets to merge symmetric belief states
    b_quant = (np.clip(state.band_belief, 0.0, 1.0) * 8).astype(np.int32)
    u_quant = (np.clip(state.band_uncertainty, 0.0, 1.0) * 4).astype(np.int32)
    last = -1 if state.last_band is None else state.last_band
    # Fast hash via tuple
    key = (last, depth, tuple(b_quant[::2]), tuple(u_quant[::4]))
    return hash(key)


class BeliefExpectimaxPlanner:
    """Bounded Belief-State Expectimax lookahead planner with stochastic pruning."""

    def __init__(
        self,
        num_bands: int = NUM_BANDS,
        *,
        depth: int = 2,
        gamma: float = 0.90,
        branch_k: int = 3,
        path_prob_threshold: float = 0.005,
        w_detect: float = 1.00,
        w_info: float = 0.25,
        w_investigate: float = 0.30,
        w_switch: float = 0.05,
        max_planning_ms: float = 6.0,
        max_nodes: int = 400,
        enable_pruning: bool = True,
        enable_caching: bool = True,
        value_critic: Any | None = None,
    ):
        self.num_bands = int(num_bands)
        self.depth = int(max(1, depth))
        self.gamma = float(np.clip(gamma, 0.0, 1.0))
        self.branch_k = int(max(1, branch_k))
        self.path_prob_threshold = float(path_prob_threshold)
        self.w_detect = float(w_detect)
        self.w_info = float(w_info)
        self.w_investigate = float(w_investigate)
        self.w_switch = float(w_switch)
        self.max_planning_ms = float(max_planning_ms)
        self.max_nodes = int(max_nodes)
        self.enable_pruning = bool(enable_pruning)
        self.enable_caching = bool(enable_caching)
        self.value_critic = value_critic

        # Transposition table: (hash, depth) -> (value, best_action)
        self.cache: dict[tuple[int, int], tuple[float, int]] = {}

        # Diagnostics & Search Counters
        self.nodes_expanded = 0
        self.nodes_pruned = 0
        self.cache_hits = 0
        self.cache_misses = 0
        self.deadline = 0.0
        self.timed_out = False

    def reset(self):
        self.cache.clear()
        self.nodes_expanded = 0
        self.nodes_pruned = 0
        self.cache_hits = 0
        self.cache_misses = 0
        self.timed_out = False

    def compute_immediate_utility(self, state: BeliefState, action: int, p_hit: float) -> float:
        """Calculates observable expected reward for scanning band `action`."""
        switch_cost = 0.0
        if state.last_band is not None and self.w_switch > 0.0:
            dist = abs(action - state.last_band) / max(1, self.num_bands - 1)
            switch_cost = self.w_switch * dist

        u = (
            self.w_detect * p_hit
            + self.w_info * float(state.band_uncertainty[action])
            + self.w_investigate * float(state.investigation_priority[action])
            - switch_cost
        )
        return float(u)

    def transition_belief(self, state: BeliefState, action: int, detected: bool) -> BeliefState:
        """Probabilistic Bayesian belief transition model without fake I/Q generation."""
        nxt = state.clone()
        age_step = 1.0 / 30.0
        nxt.scan_age = np.clip(nxt.scan_age + age_step, 0.0, 1.0)
        nxt.scan_age[action] = 0.0
        nxt.last_band = action

        # Update UCB counts
        nxt.ucb_counts *= 0.985
        nxt.ucb_counts[action] += 1.0

        if detected:
            # HIT POSTERIOR:
            # 1. Increase belief on selected band
            nxt.band_belief[action] = float(np.clip(state.band_belief[action] * 1.35 + 0.15, 0.0, 1.0))
            # 2. Sharply reduce uncertainty
            nxt.band_uncertainty[action] *= 0.25
            # 3. Update observable UCB value
            nxt.ucb_values[action] = 0.8 * nxt.ucb_values[action] + 0.2 * 0.85
        else:
            # MISS POSTERIOR:
            # 1. Suppress belief on selected band
            nxt.band_belief[action] = float(np.clip(state.band_belief[action] * 0.20, 0.0, 1.0))
            # 2. Moderately reduce uncertainty
            nxt.band_uncertainty[action] *= 0.60
            # 3. Update observable UCB value with miss value
            nxt.ucb_values[action] = 0.8 * nxt.ucb_values[action] + 0.2 * 0.02

        return nxt

    def rank_child_actions(self, state: BeliefState, k: int) -> list[int]:
        """Dynamic Top-K candidate generation at child decision nodes."""
        tot_counts = float(np.sum(state.ucb_counts))
        exp_bonus = 0.75 * np.sqrt(np.log(tot_counts + 2.0) / np.maximum(state.ucb_counts, 1e-6))
        scores = state.ucb_values + exp_bonus + 0.35 * state.band_belief + 0.10 * state.scan_age
        if state.last_band is not None:
            for b in range(self.num_bands):
                scores[b] -= 0.05 * (abs(b - state.last_band) / max(1, self.num_bands - 1))
        return list(np.argsort(-scores)[:k])

    def plan(
        self,
        root_state: BeliefState,
        top_k_candidates: list[int],
        search_depth: int | None = None,
    ) -> tuple[int, float, dict]:
        """Executes Expectimax tree search over top-K candidate actions."""
        t0 = time.perf_counter()
        target_depth = self.depth if search_depth is None else int(search_depth)
        self.deadline = t0 + (self.max_planning_ms / 1000.0)
        self.timed_out = False
        self.nodes_expanded = 0
        self.nodes_pruned = 0

        # Action ordering: sort candidates by detection probability + UCB value
        ordered_candidates = sorted(
            top_k_candidates,
            key=lambda b: root_state.band_belief[b] + root_state.ucb_values[b],
            reverse=True,
        )

        best_action = ordered_candidates[0]
        best_val = -float("inf")
        candidate_q_values: dict[int, float] = {}

        # Alpha-bound equivalent: best known value so far
        alpha = -float("inf")

        for action in ordered_candidates:
            if time.perf_counter() >= self.deadline:
                self.timed_out = True
                break

            q_val = self._evaluate_action(
                state=root_state,
                action=action,
                depth=0,
                target_depth=target_depth,
                path_prob=1.0,
                alpha=alpha,
            )
            candidate_q_values[action] = q_val

            if q_val > best_val:
                best_val = q_val
                best_action = action
                alpha = max(alpha, best_val)

        planning_time = (time.perf_counter() - t0) * 1000.0

        stats = {
            "best_action": best_action,
            "expected_value": best_val,
            "nodes_expanded": self.nodes_expanded,
            "nodes_pruned": self.nodes_pruned,
            "cache_hits": self.cache_hits,
            "planning_time_ms": planning_time,
            "timed_out": self.timed_out,
            "candidate_q_values": candidate_q_values,
        }
        return best_action, best_val, stats

    def _evaluate_action(
        self,
        state: BeliefState,
        action: int,
        depth: int,
        target_depth: int,
        path_prob: float,
        alpha: float,
    ) -> float:
        """Evaluates an action via its chance node (HIT and MISS branches)."""
        self.nodes_expanded += 1
        p_hit = float(np.clip(state.band_belief[action], 0.05, 0.95))
        p_miss = 1.0 - p_hit

        immediate = self.compute_immediate_utility(state, action, p_hit)
        if depth + 1 >= target_depth:
            if self.value_critic is not None and getattr(self.value_critic, "loaded", False):
                hit_state = self.transition_belief(state, action, detected=True)
                miss_state = self.transition_belief(state, action, detected=False)
                v_hit = self.value_critic.evaluate_leaf(hit_state.band_belief, hit_state.band_uncertainty, hit_state.scan_age, hit_state.last_band)
                v_miss = self.value_critic.evaluate_leaf(miss_state.band_belief, miss_state.band_uncertainty, miss_state.scan_age, miss_state.last_band)
                expected_leaf_v = p_hit * v_hit + (1.0 - p_hit) * v_miss
                return float(immediate + self.gamma * expected_leaf_v)
            return immediate

        # -------------------------------------------------------------
        # Branch-and-Bound Pruning:
        # Check optimistic upper bound on remaining return
        # -------------------------------------------------------------
        if self.enable_pruning and alpha > -float("inf"):
            # Max possible immediate utility in any future step is approx 1.6
            remaining_steps = target_depth - (depth + 1)
            geom_sum = (1.0 - self.gamma**remaining_steps) / max(1e-4, (1.0 - self.gamma))
            optimistic_future = 1.6 * geom_sum
            if immediate + self.gamma * optimistic_future < alpha:
                self.nodes_pruned += 1
                return immediate

        # HIT Branch
        p_path_hit = path_prob * p_hit
        hit_val = 0.0
        if not (self.enable_pruning and p_path_hit < self.path_prob_threshold):
            hit_state = self.transition_belief(state, action, detected=True)
            hit_val = self._search_decision_node(hit_state, depth + 1, target_depth, p_path_hit, alpha)
        else:
            self.nodes_pruned += 1

        # MISS Branch
        p_path_miss = path_prob * p_miss
        miss_val = 0.0
        if not (self.enable_pruning and p_path_miss < self.path_prob_threshold):
            miss_state = self.transition_belief(state, action, detected=False)
            miss_val = self._search_decision_node(miss_state, depth + 1, target_depth, p_path_miss, alpha)
        else:
            self.nodes_pruned += 1

        expected_future = p_hit * hit_val + p_miss * miss_val
        return float(immediate + self.gamma * expected_future)

    def _search_decision_node(
        self,
        state: BeliefState,
        depth: int,
        target_depth: int,
        path_prob: float,
        alpha: float,
    ) -> float:
        """Recursive decision node maximizing expected future return over dynamic top-K."""
        if depth >= target_depth or self.nodes_expanded >= self.max_nodes or time.perf_counter() >= self.deadline:
            # Leaf evaluation: max immediate utility of best single band
            p_hit_max = float(np.max(state.band_belief))
            return p_hit_max

        # Check transposition table
        cache_key = None
        if self.enable_caching:
            state_h = _hash_state(state, depth)
            cache_key = (state_h, depth)
            if cache_key in self.cache:
                self.cache_hits += 1
                return self.cache[cache_key][0]
            self.cache_misses += 1

        child_candidates = self.rank_child_actions(state, k=self.branch_k)
        best_node_val = -float("inf")
        best_child_action = child_candidates[0]

        for child_act in child_candidates:
            if time.perf_counter() >= self.deadline:
                self.timed_out = True
                break

            q = self._evaluate_action(
                state=state,
                action=child_act,
                depth=depth,
                target_depth=target_depth,
                path_prob=path_prob,
                alpha=max(alpha, best_node_val),
            )
            if q > best_node_val:
                best_node_val = q
                best_child_action = child_act

        if self.enable_caching and cache_key is not None:
            self.cache[cache_key] = (best_node_val, best_child_action)

        return best_node_val
